spring:
  application:
    name: vivet-sync-service
  after:
    datasource:
      jdbc-url: jdbc:oracle:thin:@10.37.11.199:1539/ldsdb
      username: ttsp
      password: MbB!2023Sp
      driver-class-name: oracle.jdbc.driver.OracleDriver
      hikari:
        minimum-idle: 1
        maximum-pool-size: 10
        connection-timeout: 120000
        idle-timeout: 25000
        max-lifetime: 600000
        auto-commit: true

  before:
    datasource:
      jdbc-url: jdbc:oracle:thin:@10.36.126.42:1521/viviet
      username: order_owner_vv_te
      password: order_owner_vv_te
      driver-class-name: oracle.jdbc.driver.OracleDriver
      hikari:
        minimum-idle: 1
        maximum-pool-size: 10
        connection-timeout: 120000
        idle-timeout: 25000
        max-lifetime: 600000
        auto-commit: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        generate_statistics: false
        proc:
          param_null_passing: param_null_passing
      javax:
        persistence:
          query:
            timeout: 60000
  jackson:
    time-zone: UTC
task:
  executor:
    min: 10
    max: 50
#kafka:
#  broker:
#    address: 10.36.126.132:9092,10.36.126.133:9092,10.36.126.134:9092
#  notif:
#    info:
#      topic-viviet-customer: CUSTOMER_TEST
#  topic:
#    fetch:
#      max:
#        byte: 52428800
#    partition:
#      fetch:
#        byte: 1048576
#  group:
#    id:
#      sms: VIVIET_CUSTOMER_SYNTHETIC_SERVICE
#  factory:
#    concurrency: 14

server:
  port: 9919
